theme: minima
plugins:
  - jekyll-feed

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "tutorials"
    values:
      layout: "default"


collections:
 tutorials:
  sort_by: category
  output: true
